# Permalinks
permalink:        /posts/:title.html

# Setup
# url:              //myanbin.github.io
ssl_url:          myanbin.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            '饮冰先生'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  关于代码和一切

# The tags listed as entries in the sidebar
sidebar_tags:     []

# Google Analytics tracking ID
analytics:        'UA-35742418-1'

# Fallback image and color if not overwritten for tag or post
image:            /public/img/green.jpg
color:            '#A85641'

author:
  name:           '饮冰先生'
  email:          yianbin@gmail.com
  github:         myanbin
  linkedin:       myanbin
  weibo:          yianbin
  photo:          //7nj1q2.com1.z0.glb.clouddn.com/blog!me.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是饮冰先生，热爱前端与黑客文化，喜欢与人交流分享。我的微博 [@孺子牛骑士](http://weibo.com/yianbin)


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
